### ISSUE TITLE
Error on search

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#31]
![Screenshot from 2019-12-09 10-24-05](https://user-images.githubusercontent.com/4154978/70415685-45eb6180-1a6e-11ea-843d-b0cb2bef81e9.png)

маска *.pp *.pas *.inc

```
Startup: total: 410ms, including plugins: 0ms
Python 3.7.3
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 2296, in work
    fifwork(m.observer, m.rslt, walkers, fragmer, frgfilters, m.reporter)
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 2820, in fifwork
    reporter.add_frg(fn, frgs)
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 2989, in add_frg
    self.rfrgs.append(          newRF(fn, frg))
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 2978, in newRF
    sts = LexHelper.get_src_line_styles(ed4lx, wfrg.r)
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 2567, in get_src_line_styles
    ,st=LexHelper.get_lexer_token_style(lex, tkn['style'])))
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 2378, in get_lexer_token_style
    raw_sts = {sid:th_sts[rr_ids[sid]] for sid in raw_sts}
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 2378, in <dictcomp>
    raw_sts = {sid:th_sts[rr_ids[sid]] for sid in raw_sts}
KeyError: 'Marked block'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.config/cudatext/py/cudatext.py", line 1044, in _dlg_proc_callback_proxy
    return _live[info](id_dlg, id_ctl, data=data)
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_kv_dlg.py", line 706, in ctrl_callbk
    upds    = u_callbk(self, cid, data)
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 355, in clear_if
    return mth(self, *args, **kwargs)
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 371, in timing_if
    res     = mth(self, *args, **kwargs)
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 1203, in do_acts
    upd = self.work(ag, 'fast' if scam=='s' else data)
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 2299, in work
    log(traceback.format_exc()) 
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_kv_base.py", line 97, in log
    Tr.tr=Tr()
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_kv_base.py", line 126, in __init__
    ,style='%')
  File "/usr/lib/python3.7/logging/__init__.py", line 1900, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/lib/python3.7/logging/__init__.py", line 1092, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
IsADirectoryError: [Errno 21] Is a directory: '/home/user'
```

**Comment by Alexey-T** [comment]
поиск такого `'dragonfly`

**Comment by kvichans** [comment]
Сложная ошибка. Пожалуйста, сузте до поиска в одном файле и пришлите мне его

**Comment by kvichans** [comment]
Можно временно выключить `copy_styles`, чтобы понять в каких файлах шаблон встречается

**Comment by Alexey-T** [comment]
https://github.com/graemeg/freepascal/
не могу найти один файл. ищите в папке етого репо.

**Comment by kvichans** [comment]
Найдите *первый* файл и проверьте, что на нем есть сбой.

**Comment by Alexey-T** [comment]
вот такой поиск уже дает креш. первый файл найти не могу.
![Screenshot from 2019-12-09 14-18-11](https://user-images.githubusercontent.com/4154978/70431837-ecdff580-1a8e-11ea-9ac2-d78f357b0e24.png)

видите что поле `only start dir`.

**Comment by kvichans** [comment]
Задайте в `Files` полное имя. Если есть сбой, пришлите это файл

**Comment by Alexey-T** [comment]
есть с этим
[t.zip](https://github.com/kvichans/cuda_find_in_files4/files/3939462/t.zip)

**Comment by kvichans** [comment]
спасибо - см..

**Comment by kvichans** [comment]
какой для него включить лексер?

**Comment by Alexey-T** [comment]
Pascal

**Comment by kvichans** [comment]
Проверьте на бете из ГХ. Пока ничего не менял - у меня сбоя нет

**Comment by Alexey-T** [comment]
сбой есть

**Comment by Alexey-T** [comment]
- вот конфиг
[cuda_find_in_files.zip](https://github.com/kvichans/cuda_find_in_files4/files/3939762/cuda_find_in_files.zip)
- проверьте на всей папке того репо

**Comment by kvichans** [comment]
Проверьте на версии из ГХ

**Comment by Alexey-T** [comment]
https://github.com/kvichans/cuda_find_in_files4/issues/35
снес пока плагин. :(

**Comment by kvichans** [comment]
Поймал.

Оказалось:
- У меня самого выключен механизм lexmap - поэтому мог воспроизводить только на штатных сборках
- В lexmap описаны не все ключи для стилей, а я этого не учитывал

Пока версия только в ГХ

**Comment by Alexey-T** [comment]
fixed? closing
