### ISSUE TITLE
crash if click X icon when FIF cannot close after Esc key

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#35]

**Comment by kvichans** [comment]
Проверьте на версии из ГХ

**Comment by Alexey-T** [comment]
на проверил на версии из ГХ. новая ошибка. плагин все еще виснет

```
Python 3.6
Init: cuda_project_man
Startup: 660ms, plugins: 20ms (project_man 26ms)
Init: cuda_find_in_files4
Init: cudatext
Cannot read "/home/user/Firefox_wallpaper.png": (detect) 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
Cannot read "/home/user/.ICEauthority": (detect) 'utf-8' codec can't decode byte 0xa5 in position 70: invalid start byte
Cannot read "/home/user/.pulse-cookie": (detect) 'utf-8' codec can't decode byte 0x8d in position 0: invalid start byte
[ 0.02"]Fif4D.work:2358 Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 2355, in work
    fifwork(m.observer, m.rslt, walkers, fragmer, frgfilters, m.reporter)
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 2879, in fifwork
    reporter.add_frg(fn, frgs)
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 3048, in add_frg
    self.rfrgs.append(          newRF(fn, frg))
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 3037, in newRF
    sts = LexHelper.get_src_line_styles(ed4lx, wfrg.r)
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 2619, in get_src_line_styles
    for tkn in tkns:
TypeError: 'NoneType' object is not iterable
```
жду фикса вами багов. потестите сами в Вин10. когда исправите скажите.

**Comment by Alexey-T** [comment]
снес пока ФИФ4. все плохо у вас с плагином. потестю когда будет Вин10.

**Comment by kvichans** [comment]
> проверил на версии из ГХ. новая ошибка. плагин все еще виснет

Нумерация строк в стеке ошибки не совпадает с последней версией.

Это мой косяк - не дообновил ГХ. Попробуйте еще раз из ГХ

**Comment by Alexey-T** [comment]
solved
