### ISSUE TITLE
Internal Error: name 'FPATH_PICKING' is not defined

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#39]
```
[Window Title]
CudaText

[Content]
Internal Error:
name 'FPATH_PICKING' is not defined

Please pass content of the console and the description of your steps to the plugin author.
See Help (Ctrl+H) bottom link.

Note.
To avoid error try to search with simpler options.
"Fast search" (Shift+F2) is good for the first attempt.

[OK]
```

- установка ФИФ4
- вызов длг, поиск 'wm_ncpaint' в files '*' в папке c:\dddd\dddd\lazarus\lcl\interfaces\win32

```
[ 0.01"]Fif4D.work:2378 Traceback (most recent call last):
  File "C:\Work\cudatext\app\py\cuda_find_in_files4\cd_fif4.py", line 2376, in work
    fifwork(m.observer, m.rslt, walkers, fragmer, frgfilters, m.reporter)
  File "C:\Work\cudatext\app\py\cuda_find_in_files4\cd_fif4.py", line 2867, in fifwork
    for fn     in walker.provide_path():
  File "C:\Work\cudatext\app\py\cuda_find_in_files4\cd_fif4.py", line 3759, in provide_path
    if (sort or WALK_F_PICKING):    self.observer.step_name.append(FPATH_PICKING)
NameError: name 'FPATH_PICKING' is not defined

```

**Comment by Alexey-T** [comment]
![Screenshot - 9_19_2020 , 2_19_19 PM](https://user-images.githubusercontent.com/4154978/93666047-a5f24800-fa83-11ea-904f-591d01850653.png)

**Comment by Alexey-T** [comment]
cuda_fif4.json
```
{
  "opts": {
    "in_reex": false,
    "in_case": false,
    "in_word": false,
    "in_what": "",
    "wk_fold": "",
    "wk_incl": "",
    "wk_excl": "",
    "wk_dept": 0,
    "wk_sort": "",
    "wk_agef": "",
    "wk_skip": "",
    "wk_enco": [
      "cp1251",
      "utf8",
      "detect"
    ],
    "wk_sycm": "",
    "wk_syst": "",
    "rp_cntx": false,
    "rp_cntb": 0,
    "rp_cnta": 0,
    "rp_time": false,
    "rp_lexa": false,
    "rp_lexp": false,
    "rp_trfm": "P_LL",
    "rp_relp": true,
    "rp_shcw": false,
    "vw": {
      "mlin": false,
      "mlin_h": 70,
      "rslt_h": 100,
      "what_l": [
        ""
      ],
      "fold_l": [
        ""
      ],
      "incl_l": [
        ""
      ],
      "excl_l": [
        ""
      ]
    },
    "us_focus": "wk_incl",
    "ps_pset": [],
    "vs_defs": []
  },
  "cuda": {
    "opts": {
      "in_reex": false,
      "in_case": false,
      "in_word": false,
      "in_what": "wm_ncpaint",
      "wk_fold": "C:\\fpcupdeluxe\\fpcupdeluxe\\lazarus\\lcl\\interfaces\\win32",
      "wk_incl": "*",
      "wk_excl": "",
      "wk_dept": 0,
      "wk_sort": "",
      "wk_agef": "",
      "wk_skip": "",
      "wk_enco": [
        "cp1251",
        "utf8",
        "detect"
      ],
      "wk_enco_ms": {},
      "wk_sycm": "",
      "wk_syst": "",
      "rp_cntx": false,
      "rp_cntb": 0,
      "rp_cnta": 0,
      "rp_time": false,
      "rp_lexa": false,
      "rp_lexp": false,
      "rp_trfm": "P_LL",
      "rp_relp": true,
      "rp_shcw": false,
      "vw": {
        "mlin": false,
        "mlin_h": 70,
        "rslt_h": 100,
        "what_l": [
          "wm_ncpaint"
        ],
        "fold_l": [
          "C:\\fpcupdeluxe\\fpcupdeluxe\\lazarus\\lcl\\interfaces\\win32"
        ],
        "incl_l": [
          "*"
        ],
        "excl_l": []
      },
      "us_focus": "di_rslt",
      "ps_pset": [],
      "vs_defs": []
    }
  }
}
```

**Comment by kvichans** [comment]
Очень странная ошибка "комплексации".
`FPATH_PICKING` объявлена в соседнем модуле `cd_fif4_cs.py` (как и множесто других используемых в `cd_fif4.py`).
Разбираюсь...

**Comment by Alexey-T** [comment]
повтор есть?

**Comment by kvichans** [comment]
Нету. Но на версии для Куд еще не перепроверил

**Comment by Alexey-T** [comment]
В cd_fif4_cs.py нет этого Ид!

**Comment by Alexey-T** [comment]
в ГХ совсем другой файл!

**Comment by kvichans** [comment]
О! спасибо, поправлю

**Comment by Alexey-T** [comment]
ждем-с

**Comment by Alexey-T** [comment]
?

**Comment by kvichans** [comment]
Нда уж..
Оказалось, что я так НЕ публиковал ФФ4 с заменами. Он бы в бете (в ГХ) с июня.

ОПУБЛИКОВАЛ.
Сори, навертелся по работе.
