### ISSUE TITLE
Error in Arch Linux

### ISSUE THREAD

**Issue by loziniak** [kvichans/cuda_find_in_files4#60]
From CudaText (version 1.126.0.0) console:
```
Python 3.9
Startup: 270ms, plugins: 0ms ()
Init: cuda_find_in_files4
Traceback (most recent call last):
  File "/mnt/share/bin/cudatext-linux-gtk2-amd64-1.126.0.0/py/cuda_find_in_files4/__init__.py", line 1, in <module>
    from .cd_fif4 import *
  File "/mnt/share/bin/cudatext-linux-gtk2-amd64-1.126.0.0/py/cuda_find_in_files4/cd_fif4.py", line 1748
    ),(*mn_i4op
       ^
SyntaxError: can't use starred expression here
```

**Comment by Alexey-T** [comment]
@kvichans Py 3.9 error again. Pls fix?

**Comment by kvichans** [comment]
ToDo. This week

**Comment by Alexey-T** [comment]
@loziniak Fixed, plugin updated.
@kvichans Pls close.
