### ISSUE TITLE
Error when trying to open search

### ISSUE THREAD

**Issue by thatfuckingbird** [kvichans/cuda_find_in_files4#68]
CudaText Qt5 on Linux, version 1.155.3.0.
Installed FiF4 from the addon manager.
When i try to open the find window, I get the following error:

```
Init: cuda_find_in_files4
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 355, in show_dlg_and_find_in_tab
    def show_dlg_and_find_in_tab(self): return show_fif4(d(work='in_tab'))
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 398, in show_fif4
    the_fif4    = the_fif4 if the_fif4 else Fif4D(run_opts)
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 699, in __init__
    m.init_layout()
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 1856, in init_layout
    ),rp_cntx=d(tp='chbt' ,tid='di_menu'  ,x=cntx_x       ,w=CTXW     ,cap=m.cntx_ca(),hint=cntx_hi               ,p='pt'                 # &-
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 526, in <lambda>
    cntx_ca     = lambda self: cut_amp(Fif4D.CNTX_CA(self.opts))
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 439, in <lambda>
    if 'win'!=DESKTOP and re.search(r'&\W') else \
TypeError: search() missing 1 required positional argument: 'string'
ERROR: Exception in CudaText for show_dlg_and_find_in_tab: TypeError: search() missing 1 required positional argument: 'string'
```

**Comment by Alexey-T** [comment]
@kvichans 
replace line 439 with
```
cut_amp     = lambda cap: cap.replace('&', '') \
                            if 'win'!=DESKTOP and re.search(r'&\W', cap) else \
                          cap
```

**Comment by kvichans** [comment]
Сори!

**Comment by Alexey-T** [comment]
solved now. plugin updated.

**Comment by thatfuckingbird** [comment]
I can confirm it works now.
Thank you!

**Comment by Alexey-T** [comment]
@kvichans pls, update code in GH too.

**Comment by kvichans** [comment]
ok
