### ISSUE TITLE
lib missed

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#7]
```
Startup: total: 900ms, including plugins: 90ms
Python 3.6.8
Loading toolbar config
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 21, in <module>
    try:    from    cuda_kv_base    import *        # as separated plugin
ModuleNotFoundError: No module named 'cuda_kv_base'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/__init__.py", line 1, in <module>
    from .cd_fif4 import *
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 22, in <module>
    except: from     .cd_kv_base    import *        # as part of this plugin
ModuleNotFoundError: No module named 'cuda_find_in_files4.cd_kv_base'
```

**Comment by kvichans** [comment]
Нужно установить из ГХ плаги
cuda_kv_dlg
cuda_kv_base
