### ISSUE TITLE
crash with KvLib, KvBase releases

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#8]
```
Startup: total: 860ms, including plugins: 110ms
Python 3.6.8
Loading toolbar config
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 309, in show_dlg
    def show_dlg(self):     return Fif4D().show()
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 478, in __init__
    self.opts.update(fget_hist('opts', self.opts))
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 40, in <lambda>
    ,object_pairs_hook=dcta)
TypeError: get_hist() got an unexpected keyword argument 'object_pairs_hook'
Highlight Occurrences: load options
```

**Comment by kvichans** [comment]
Нужно обновить из ГХ до версии с `json_kwargs`
```python
def get_hist(key_or_path, default=None, module_name='_auto_detect', to_file=PLING_HISTORY_JSON, 
**json_kwargs)
```

**Comment by Alexey-T** [comment]
может обновите эти либы релизы?

**Comment by kvichans** [comment]
Нет. Пока в `cuda_kv_*` идут мелкие доделки. 
Нужно обновлять из ГХ
